CREATE TABLE public.outlets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID unik, Primary Key
  code TEXT UNIQUE NOT NULL, -- Contoh: A1, B12 (Harus unik)
  block TEXT, -- Contoh: A, B, C, D
  name TEXT NOT NULL, -- Nama Outlet (Contoh: Takoyaki Enak 1)
  category TEXT, -- Kategori Makanan (Contoh: Takoyaki)
  image_url TEXT, -- URL gambar utama (dari Supabase Storage)
  wa TEXT, -- Kontak WhatsApp
  ig TEXT, -- Instagram
  gofood TEXT, -- Nama akun GoFood
  shopee TEXT, -- Nama akun ShopeeFood
  grab TEXT, -- Nama akun GrabFood
  is_active BOOLEAN DEFAULT TRUE, -- Opsional: Untuk menandai apakah outlet masih aktif
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.menus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID unik, Primary Key
  outlet_id BIGINT REFERENCES public.outlets(id) ON DELETE CASCADE, -- Foreign Key ke tabel outlets
  name TEXT NOT NULL, -- Nama Menu
  price BIGINT NOT NULL, -- Harga Menu (gunakan BIGINT untuk angka besar)
  image_url TEXT, -- URL gambar menu (hanya untuk Menu Spesial)
  is_special BOOLEAN DEFAULT FALSE, -- Opsional: Untuk membedakan menu spesial dan menu lainnya
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);